version: "3.8"

services:
  webApi:
    image: apipokemon:dev
    ports:
      - "8080:8080"
    networks:
      - pokemon-network
    depends_on:
      - db_pokemon
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db_pokemon:
    image: postgres:latest
    container_name: db_pokemon
    volumes:
      - vl_db_postgres_pokemon:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=pokemon_db
      - POSTGRES_PASSWORD=EA_2023*
    ports:
      - "5432:5432"
    networks:
      - pokemon-network

volumes:
  vl_db_postgres_pokemon:

networks:
  pokemon-network:
    driver: bridge